<a href="https://colab.research.google.com/github/Geonus99/AI_26/blob/main/numpy_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [9]:
# 파이썬 리스트 수치연산과 넘파이 배열 수치연산은 엄연히 다름
[1,2,3,4,5] * 2 # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
arr_1 * 2 # array([ 2,  4,  6,  8, 10])

array([ 2,  4,  6,  8, 10])

In [10]:
# 2차원 배열
arr_2 = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# 3차원 배열
arr_3 = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11,12]],
                  [[13, 14, 15],
                   [16, 17, 18]]])
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [14]:
# 넘파이 배열의 데이터 타입
arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1.dtype)

int64


In [17]:
print(np.array([1,2,3]).dtype) # int64 기본
print(np.array([1, 2, 3], dtype='int8').dtype) # int8 지정
print(np.array([1, 2, 3], dtype='i1').dtype) # 1바이트 정수형 데이터 타입 = int8

int64
int8
int8


In [18]:
# 데이터 분석에 파이썬 리스트가 아니라 넘파이 배열을 쓰는 이유
# 1. 메모리 사용 효율이 좋고, 계산 속도가 빠름
# 2. 선형 대수 연산 지원
# 3. 벡터화 연산 지원
# 3.1 :  벡터화 연산 지원 : 배열의 모든 요소에 대해 루프 없이 한 번에 연산을 수행하는 연산 기법
# 3.2 :  요소의 값을 한번에 연산하는 요소별 연산, 값을 배열로 펼쳐서 적용하는 브로드캐스팅

In [21]:
ndarray_1 = np.array([1, 2, 3]) # 넘파이 배열
ndarray_2 = np.array([4, 5, 6]) # 넘파이 배열
list_1 = [1,2,3] # 파이썬 리스트
list_2 = [4,5,6] # 파이썬 리스트

print(ndarray_1 + ndarray_2) # [5 7 9]
print(list_1 + list_2) # [1, 2, 3, 4, 5, 6]
# 넘파이 배열은 일대일 대응해서 더함 -> 요소별 연산
# 파이썬으로 넘파이 같은 연산을 할려면
# result_list = [x+y for x, y in zip(list_1, list_2)] 으로 비효율적

print(ndarray_1 * 2) # [2 4 6] = [1,2,3]*[2,2,2]
print(list_1 * 2) # [1, 2, 3, 1, 2, 3]
# 배열 간의 크기가 달라도 작은 배열을 자동으로 확장하여
# 같은 크기로 맞춘 후 연산을 수행 -> 브로드캐스팅

[5 7 9]
[1, 2, 3, 4, 5, 6]
[2 4 6]
[1, 2, 3, 1, 2, 3]


In [26]:
a = np.array([2, 3, 4]) # 넘파이 정수형 배열 생성
print(a.dtype)
b = np.array([2.1, 3.2, 4.3]) # 넘파이 실수형 배열 생성
print(b.dtype)
c = np.array(('i','j','k')) # 파이썬 튜플로 넘파이 배열 생성
print(c.dtype)
d = np.array((True, True, False)) # 넘파이 논리형 배열 생성
print(d.dtype)
e = np.array(['ab','cd','e'], dtype='<U2') # 문자열 길이를 조절하여 배열 생성
print(e.dtype)

int64
float64
<U1
bool
<U2


In [28]:
# a라는 변수에 (3, 4) 크기의 넘파이 2차원 배열 생성
a = np.arange(12).reshape(3, 4) # 함수를 연이어 사용하는 방식 : 체이닝
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
print(a.shape) # 배열의 차원과 차원의 크기 반환
print(a.ndim) # 배열의 차원 수 반환
print(a.dtype) # 배열의 데이터 타입 반환
print(a.itemsize) # 배열의 각 요소의 크기를 바이트 단위로 반환

(3, 4)
2
int64
8


In [35]:
# 각 학급에 4명의 학생, 각 학생이 3과목의 시험점수를 가지고 있는 배열 생성
# 예시 : 3개의 학급, 각 학급에 4명의 학생, 각 학생당 국어, 영어, 수학 점수
scores = np.random.randint(0, 101, size=(3, 4, 3))

# 학급별, 학생별, 과목별 점수를 출력
print("학급별 학생들의 점수 배열 (3차원 배열):")
print(scores)

# 학급, 학생, 과목별로 점수 출력
for class_idx in range(scores.shape[0]):
  print(f"\nClass {class_idx + 1}")
  for student_idx in range(scores.shape[1]):
    korean, english, math = scores[class_idx, student_idx]
    print(f"Student {student_idx + 1} - Korean : {korean}, English : {english}, Math : {math}")

학급별 학생들의 점수 배열 (3차원 배열):
[[[ 33  35  86]
  [ 62  76  23]
  [ 76  96 100]
  [ 82  41  74]]

 [[ 37  27  58]
  [ 26  23  25]
  [ 98  63  85]
  [ 25  61  41]]

 [[ 95   0  16]
  [ 97  35 100]
  [  2  86  12]
  [ 97   8  76]]]

Class 1
Student 1 - Korean : 33, English : 35, Math : 86
Student 2 - Korean : 62, English : 76, Math : 23
Student 3 - Korean : 76, English : 96, Math : 100
Student 4 - Korean : 82, English : 41, Math : 74

Class 2
Student 1 - Korean : 37, English : 27, Math : 58
Student 2 - Korean : 26, English : 23, Math : 25
Student 3 - Korean : 98, English : 63, Math : 85
Student 4 - Korean : 25, English : 61, Math : 41

Class 3
Student 1 - Korean : 95, English : 0, Math : 16
Student 2 - Korean : 97, English : 35, Math : 100
Student 3 - Korean : 2, English : 86, Math : 12
Student 4 - Korean : 97, English : 8, Math : 76


In [42]:
# zeros() 함수는 shape에 모양을 지정하여 모든 요소를 0으로 초기화
# (3, 4) 크기의 배열을 생성하여 0으로 채움
print(np.zeros((3, 4)))
# (3, 4) 크기의 배열을 데이터 타입을 정수로 생성한 후, 0으로 채움
print(np.zeros((3, 4), dtype=int))

# 모든 요소가 1로 초기화된 넘파이 배열
print(np.ones((2, 3, 4), dtype=int))

# 모든 요소가 비어 있는 넘파이 배열
print(np.empty((2, 3)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.48842190e-315 0.00000000e+000 1.49661369e-315]
 [6.64071980e-310 3.64751225e-258 3.63151834e-297]]


In [46]:
# arange() 함수로 넘파이 배열 만들기

# np.arange(start, stop, step, dtype)
# start: 시작값(기본:0), stop : 종료값, step: 배열사이간격(기본:1), dtype:타입(자동)
# 10 이상 30 미만까지 5 간격
print(np.arange(10, 30, 5))
# 0 이상 2 미만까지 0.3 간격
print(np.arange(start = 0, stop = 2, step = 0.3))

# linspace() 함수로 넘파이 배열 만들기
# np.linspace(start, stop, num, endpoint, retstep, dtype)
# start: 시작값, stop: 종료값, num: 배열 요소 개수(기본:50), endpoint: 종료값을 포함 여부를 나타내는 논리형 데이터(기본:True)
# retstep: 요소 사이 간격 반환 여부를 나타내는 논리형 데이터(기본:False), True로 설정하면 간격도 함께 반환
# dtype : 타입(기본:실수)
print(np.linspace(start = 1, stop = 10, num = 10, dtype = int))

# arange() 함수
# 일정 간격 강조해야하는 데이터 때 사용하기 좋음(시간, 날짜)
# 끝 범위 포함 안함
# np.arange(0, 10, 3) -> [0,3,6,9]

# linspace() 함수
# 일정한 구간 데이터 생성할때 사용
# 데이터를 시각화하거나 구간별 통계량 계산시 유용
# np.linspace(0, 10, 4) -> [0.0, 3.33, 6.67, 10.0]

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
# 요소별 연산으로 사칙 연산
a = np.array([10,20,30,40])
b = np.arange(start=1, stop=5)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [50]:
A = np.array([[1, 1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
print(A*B)
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [51]:
# 요소별 연산으로 비교 연산
A = np.array([1, 2, 3, 4])
B = np.array([1, 1, 3, 4])
print(A>B)
print(A==B)

[False  True False False]
[ True False  True  True]


In [54]:
student1_scores = np.array([85,90,78])
student2_scores = np.array([92, 88, 95])

print("학생 1의 점수 : ", student1_scores)
print("학생 2의 점수 : ", student2_scores)

total_scores = student1_scores + student2_scores
print("두 학생의 총점 : ", total_scores)

average_scores = total_scores / 2
print("두 학생의 평균 점수 : ", average_scores)

student1_total = np.sum(student1_scores)
student2_total = np.sum(student2_scores)
student1_average = np.mean(student1_scores)
student2_average = np.mean(student2_scores)

print("학생 1의 총점 : ", student1_total)
print("학생 1의 평균 점수 : ", student1_average)
print("학생 2의 총점 : ", student2_total)
print("학생 2의 평균 점수 : ", student2_average)

학생 1의 점수 :  [85 90 78]
학생 2의 점수 :  [92 88 95]
두 학생의 총점 :  [177 178 173]
두 학생의 평균 점수 :  [88.5 89.  86.5]
학생 1의 총점 :  253
학생 1의 평균 점수 :  84.33333333333333
학생 2의 총점 :  275
학생 2의 평균 점수 :  91.66666666666667


In [57]:
# sqrt() 함수는 제곱근 계산하여 반환
A = np.array([4, 16, 25])
print(np.sqrt(A))

[2. 4. 5.]


In [59]:
a = np.arange(8).reshape(2,4)**2
print(a)

print(a.sum())
print(a.mean())
print(a.min())
print(a.cumsum())
print(a.argmax())

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
0
[  0   1   5  14  30  55  91 140]
7


In [61]:
# 0부터 8미만 까지 출력 (2,4) 크기로 재가공하고 제곱하여 출력
a = np.arange(8).reshape(2,4)**2

# axis = 0은 열 기준으로 연산
print(a.mean(axis = 0))
# axis = 1은 행 기준으로 연산
print(a.max(axis = 1))

[ 8. 13. 20. 29.]
[ 9 49]


In [69]:
a = np.array([0, 1, 2, 3, 4 ,5])
print(a)
print(a[0])
print(a[3])
print(a[0:3])
b = np.array([[0,1,2], [3,4,5]])
print(b)
print(b[1,0])
print(b[1,2])


[0 1 2 3 4 5]
0
3
[0 1 2]
[[0 1 2]
 [3 4 5]]
3
5


In [72]:
a= np.arange(12).reshape(3,4)
print(a)

b = a>4
print(b)
print(a[b].shape)
a[b] = 1000
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
(7,)
[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [74]:
a = np.array(['a','b','c','d','e','f','g','h'])
i = np.array([1,1,3,4])

print(a[i])
j = np.array([[3,4],[5,6]])

print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [75]:
# 배열의 요소 재배열
b = np.array(['a','b','c','d'])
k = np.array([3, 2, 1, 0])

b = b[k]
print(b)

['d' 'c' 'b' 'a']


In [80]:
# reshape() 함수 : 원본 배열 변경하지 않고 새로운 배열 반환
# 데이터 순서는 유지되며 배열의 차원이나 모양만 변경
# 인수로 -1을 전달하면 자동으로 요소 개수를 맞춰줌
a= np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)

b = a.reshape(2,6)
print(b)
print(b.shape)

print(a)
print(a.shape)

c = a.reshape(-1, 3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [82]:
# resieze() : 원본 배열 자체를 변형, 새 배열을 반환하지 않음
a = np.arange(12)
a.resize(4,3)
print(a)
print(a.shape)
print(a.resize(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
None


In [83]:
# ravel() : 다차원 배열을 1차원 배열로 평탄화(다차원 배열의 모든 요소를 하나의 행으로 나열)
# reshape() 함수에 -1 도 됨
a = np.arange(12).reshape(3,4)

print(a.ravel())
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [84]:
# 전치 연산 : 행렬에서 행과 열을 서로 바꾸는 연산
A = np.arange(12).reshape(2,6)
print(A)

# .T : [2, 6]을 [6,2] 반환으로 전치 변환
print(A.T)
print(A.T.shape)

# 만약 전치 형태로 원본 A 배열에 저장하고 싶다면, A배열메 A.T 값을 할당
A = A.T
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)


In [85]:
# 배열 합치기
# vstack() 수직, hstack() 수평
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [86]:
# 배열 분할하기
# vsplit(), hsplit()
a = np.arange(12).reshape(2,6)
print(a)

print(np.vsplit(a,2))
print(np.hsplit(a, 3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
